### ISSUE TITLE
MapPage: adicionar cidade no BD

### ISSUE THREAD

**Issue by keceoliveira** [ResidenciaTICBrisa/T2G1-IA-Gloria#221]
### Descrição do Problema

O campo de cidade no Banco de Dados está definido como não obrigatório. No entanto, essa informação é extremamente necessária e não pode ser omitida.

### Solução proposta 

A API Open Street Map - Nomination, utilizada na aplicação, nem sempre retorna a cidade em todos os endereços coletados. Isso causava um erro quando os dados eram retornados para o Banco de Dados, pois o campo cidade podia estar vazio. Para contornar esse problema, o campo cidade foi definido como não obrigatório no BD. Porém, após uma reunião com o cliente, foi ressaltada a importância desse dado, e a correção foi solicitada.

### Tarefas e critérios de aceitação

-  [ ]  Ao preencher o formulário, os campos de cidade e estado devem ser enviados corretamente ao Banco de Dados
- [ ] Os dados contidos nos campos estado e cidade devem estar disponíveis para uso em qualquer página da aplicação conforme a necessidade

**Comment by izabellerivas** [comment]
Inviável considerando as APIs gratuitas disponíveis
